# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build Frontappapp

on:
  push:
    branches:
    - main
    - githubaction

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name : Check Java version
      run: java -version
    - name: MAven version check
      run: mvn -version

    - name: front end dir change
      run: cd ./frontapp && ./mvnw clean package 
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t frontkapp -f ./Dockerfile ./frontapp --tag ghcr.io/attilaszegedi/block3/homework-frontapp:springboot3 && docker push ghcr.io/attilaszegedi/block3/homework-frontapp:springboot3


   

