# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build Backapp

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name : Check Java version
      run: java -version
    - name: MAven version check
      run: mvn -version

    - name: front end dir change
      run: cd ./frontapp

    - name: Build with Maven
      run: mvn -B clean package 
      
    - name: Logging into docker
      run: docker login ghcr.io -u attilaszegedi -p ${{ github.token }}

    - name: Build docker
      run: docker build -t frontapp -f ./Dockerfile ./frontapp

    - name: Publish docker
      run: docker push ghcr.io/attilaszegedi/cubix/homework-2-frontapp:actions


   

